version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/logs
    volumes:
      - ./data/db:/data/db
      - ./logs/mongo:/data/logs
    ports:
      - 27017:27017
    command: [--auth]

  mongo-client:
    image: mongoclient/mongoclient
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./data/client:/data/db
    environment:
      MONGO_URL: mongodb://username:password@mongodb:27017/notes
    links:
      - mongodb
