version: '3'

services:
  db:
    container_name:  database
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    restart: always
    ports:
      - "1234:80"
    environment:
      - PMA_HOST=db
      # - PMA_ARBITRARY=1
