version: '3'

services:
  db:
    container_name:  database
    image: mariadb
    ports:
      - "localhost:3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:  # Set up mysql database name and password
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: notes
      MYSQL_USER: username
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    restart: always
    ports:
      - "1234:80"
    environment:
      - PMA_HOST=db
      # - PMA_ARBITRARY=1
